[package]
name = "parser-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = { workspace = true }
calamine = "0.26.1"
docx-rs = "0.4.17"
infer = "0.16.0"
lazy_static = "1.4.0"
mime = "0.3.17"
pdf-extract = "0.8.0"
regex = "1.11.1"
rusty-tesseract = "1.1.10"
# tempfile is only used for image parsing since Tesseract needs a file path
tempfile = "3.9.0"
zip = "2.2.2"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "parsing_benchmark"
harness = false
