[package]
name = "parser-web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
actix-multipart = "0.7"
parser-core = { path = "../parser-core" }
