name: CD Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pre-deploy-checks:
    name: Pre-deployment Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libtesseract-dev libleptonica-dev libclang-dev
          version: 1.0

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true

      # TODO: Find way to fail when version already exists on crates.io
      - name: Dry run publish for core crate
        uses: actions-rs/cargo@master
        with:
          command: publish
          args: -p parser-core --dry-run
