name: CI Checks

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libtesseract-dev libleptonica-dev libclang-dev
          version: 1.0

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libtesseract-dev libleptonica-dev libclang-dev
          version: 1.0

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
