name: CI Checks

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  test:
    name: Format, Lint, and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libtesseract-dev libleptonica-dev libclang-dev
          version: 1.0

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Format
        uses: actions-rs/cargo@master
        with:
          command: fmt
          args: --all -- --check

      - name: Lint
        uses: actions-rs/cargo@master
        with:
          command: clippy
          args: --all -- -D warnings

      - name: Test
        uses: actions-rs/cargo@master
        with:
          command: test
          args: --all
