name: Publish to crates.io

permissions:
  contents: read

on:
  workflow_run:
    workflows: ["CI Checks", "CD Checks"]
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Publish core crate
        uses: actions-rs/cargo@master
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        with:
          command: publish
          args: -p parser-core
