name: Publish Core Crate

on:
  # Automatic publishing on push to main (excluding version bump commits)
  push:
    branches:
      - main
    paths:
      - 'crates/core/**'
      - '.github/workflows/publish.yml'
    paths-ignore:
      - '**/*[skip ci]*'
  
  # Manual workflow dispatch with version type parameter
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

# Add permissions for GitHub token
permissions:
  contents: write
  packages: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump core crate version
        id: version
        working-directory: ./crates/core
        run: |
          # Determine version bump type - default to patch for auto-triggered workflow
          BUMP_TYPE="${{ github.event.inputs.version_bump || 'patch' }}"
          echo "Using version bump type: $BUMP_TYPE"
          
          # Get current version
          CURRENT_VERSION=$(grep '^version =' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "Current version: $CURRENT_VERSION"
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
          # Increment version based on bump type
          cargo set-version --bump $BUMP_TYPE
          
          # Get new version
          NEW_VERSION=$(grep '^version =' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
          # Create version branch name
          VERSION_BRANCH="version-bump-$NEW_VERSION"
          echo "version_branch=$VERSION_BRANCH" >> $GITHUB_OUTPUT
          
          # Create branch for version bump
          git checkout -b $VERSION_BRANCH
          
          # Commit the version bump
          git add Cargo.toml
          git commit -m "Bump parser-core version to $NEW_VERSION [skip ci]"

      - name: Push changes
        run: git push --set-upstream origin ${{ steps.version.outputs.version_branch }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.version.outputs.version_branch }}
          delete-branch: true
          title: "Bump parser-core version to ${{ steps.version.outputs.new_version }}"
          body: |
            Automated version bump by GitHub Actions
            - Bumped parser-core from ${{ steps.version.outputs.current_version }} to ${{ steps.version.outputs.new_version }}
          base: main
          labels: |
            version-bump
            automated

      - name: Publish to crates.io
        working-directory: ./crates/core
        # Only proceed with publishing on workflow_dispatch or explicitly approved PRs
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
        run: |
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}